Passer à BS4
InseeFrLab/utilitr-template pull request #14
Opened 2021-03-24 18:53 UTC by oliviermeslin

2021-03-25 00:21 UTC, RLesur requested changes
Gros boulot ! J'ai repéré plusieurs pistes d'amélioration

2021-03-25 00:21 UTC, RLesur commented on R/build_website.R
> +  }
Tu es sûr ? ça améliore le gitbook ?

2021-03-25 00:21 UTC, RLesur commented on R/build_website.R
> +  }
Un point de détail, il y a 2 conventions différentes ici : 
- pour les fichiers CSS, c'est seulement le nom de fichier d'utilisé
- pour les fichiers JS, il y a le nom du répertoire parent

Pourquoi ne pas retenir la même convention ? ce serait plus simple, non ?

2021-03-25 00:21 UTC, RLesur commented on R/build_website.R
> +  print(paste0("default_dep: ", default_dep))
à quoi ça sert ? :thinking:

2021-03-25 00:21 UTC, RLesur commented on R/build_website.R
> +#' @param ... Additional arguments passed to \code{bookdown::\link{gitbook}()}.
```suggestion
#' @param ... Additional arguments passed to \code{bookdown::\link{bs4_book}()}.
```

2021-03-25 00:21 UTC, RLesur commented on R/build_website.R
> +#' @param extra_dependencies Additional HTML dependencies
Ce n'est pas cohérent de gérer seulement `extra_dependencies`. Si on voulait faire les choses proprement, il faudrait gérer les autres paramètres. En effet, si on passe un des arguments `includes`, `new_session`, `theme` ou `pandoc_args` dans le dots argument, on fait planter cet output format.

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  button[id="print"],
C'est plus efficace d'écrire 
```suggestion
  #print,
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
c'est un peu cyclique comme affaire

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      content: var(--date-fiche);
Tiens, on mélange :gb: et :fr: ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  footer[class="bg-primary text-light mt-5"] {
On ne peut pas simplifier ce sélecteur ? `footer` seul, ça ne suffit pas ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +.col-md-9 {
ce n'est pas très sémantique comme sélecteur. Ce ne serait pas `main` par hasard que tu vises ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  .col-xl, .col-xl-auto, .col-xl-12, .col-xl-11, .col-xl-10, .col-xl-9, .col-xl-8, .col-xl-7, .col-xl-6, .col-xl-5, .col-xl-4, .col-xl-3, .col-xl-2, .col-xl-1, .col-lg, .col-lg-auto, .col-lg-12, .col
C'est un truc de bélier, ça ! :exploding_head: 
C'est l'enfer pour comprendre ce que tu veux faire là

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +/* Ecraser les réglages de bs4 */
```suggestion
/* Tweak Bootstrap 4 theme */
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  /* Masquer des choses */
```suggestion
  /* Hide some elements */
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  /* Mise en forme du titre de première page */
```suggestion
  /* First page styling */
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  /* Enlever la couleur de fond du code */
```suggestion
  /* Remove code background color */
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  /* Renuméroter les pages */
```suggestion
  /* Reset page numbers */
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  /* Enlever les deux premières pages */
Ah bon ? on a besoin de faire ça ??? il faudrait peut être documenter un peu plus car là, c'est fou.

```suggestion
  /* Remove the first two pages */
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  div[class="chapter-nav"] {
Pourquoi pas ça ?

```suggestion
  div.chapter-nav {
```

 ce n'est pas équivalent mais sinon ça signifie que tu as un sélecteur hyper tricky

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default-fonts.css
> +  @import "https://fonts.googleapis.com/css?family=Newsreader";
On est vraiment certain que l'API v1 de Google Fonts permet d'exploiter cette police variable ?
J'avais retenu que pour utiliser une police variable (tu utilises `opsz` plus bas) il fallait utiliser l'API v2 cf. https://developers.google.com/fonts/docs/css2

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default-page.css
> +*/
A quoi ça sert de fusionner des règles commentées ? On peut les supprimer, non ?

```suggestion
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default-page.css
> +a[class='footnote-ref'] {
Plus sobre, plus sémantique et plus efficace

```suggestion
.footnote-ref {
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default.css
> +  --date-fiche: "Test date fiche";
```suggestion
  --date-fiche: "Date inconnue";
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default.css
> +  */
On supprime ces lignes commentées ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default.css
> + border-left: 2rem solid var(--background-color-chunk-output);
On rajoute ces lignes commentées ? :thinking:

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default.css
> +*/
On supprime ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/css/default.css
> +*/
On supprime ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/html/print_button.html
> +  <i class="glyphicon glyphicon-print" type="submit" onclick="window.PagedPolyfill.preview().then(() => {document.body.style.cssText='min-width: unset !important'; window.print();})" style= "padding-
On ne peut pas laisser ça comme ça, c'est trop illisible. Tu peux accepter la modification ci-dessous ainsi que celle-ci : 

Il faut aussi déplacer le style inline dans une feuille de style.

```suggestion
  <i class="glyphicon glyphicon-print" type="submit" onclick="printWithPagedJS()" style= "padding-left: 5px; color: #cf581b;">
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/html/header_polyfill.html
> +</script>
```suggestion

  window.printWithPagedJS = () => {
    window.PagedPolyfill.preview().then(() => {
      document.body.style.cssText = 'min-width: unset !important';
      window.print();
    });
  };
</script>
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/html/print_button.html
> +  <b style = "color: #cf581b; padding-left: 5px;">Imprimer en A4</b>
Il faut aussi déplacer le style inline dans une feuille de style

```suggestion
  <b style = "color: #cf581b; padding-left: 5px;">Imprimer</b>
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/js/css-print-toggle.js
> +const screenRules = [];
Ca, c'est clairement du code que tu as repompé : 
- est-il vraiment utile ? j'en doute
- quelle est la licence ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/js/css-print-toggle.js
> +module.exports = {
Tu utilises déjà les modules ? :rofl:

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/js/date-fiche.js
> +document.documentElement.style.setProperty('--date-fiche', `'${message}'`);
Ca ne sert à rien de polluer avec tous ces objets globaux

```suggestion
{
  let dd = String(today.getDate()).padStart(2, '0');
  let mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0
  let yyyy = today.getFullYear();
  let today = `${dd}/${mm}/${yyyy}`;
  let message = 'Source: www.utilitr.org, date : ' + today;

  document.documentElement.style.setProperty('--date-fiche', `'${message}'`);
}
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/resources/html/header_polyfill.html
> +  PagedConfig = {auto: false};
Plus explicite et plus safe

```suggestion
  window.PagedConfig = {auto: false};
```

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +#  download: [["README.md", "PDF"]]
A quoi sert cette modification ?

2021-03-25 00:21 UTC, RLesur commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +  new_session: yes
Je suis vraiment étonné que ça fonctionne. As-tu testé ? Logiquement, je m'attendrais à ce que ça plante car `new_session` est en dur dans l'output format

```suggestion
  new_session: yes
```

2021-03-25 00:21 UTC, RLesur commented on inst/templates/gitbook.html
> +
C'est du code dupliqué, ça. Tu ne peux pas réutiliser les includes ?

2021-03-25 06:25 UTC, oliviermeslin commented on R/build_website.R
> +  print(paste0("default_dep: ", default_dep))
J'avais un doute sur le contenu des dépendances, donc j'ai mis ça pour imprimer le contenu. Je l'enlève.

2021-03-25 06:27 UTC, oliviermeslin commented on R/build_website.R
> +#' @param extra_dependencies Additional HTML dependencies
@linogaliana : tu peux régler ce point? Je ne me sens pas de modifier la fonction moi-même.

2021-03-25 06:30 UTC, oliviermeslin commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +#  download: [["README.md", "PDF"]]
Aucune idée. @linogaliana : une idée?

2021-03-25 06:32 UTC, oliviermeslin commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +  new_session: yes
Oui, je l'ai testé des dizaines de fois.

2021-03-25 06:33 UTC, oliviermeslin commented on R/build_website.R
> +  }
Non, je l'ai ajouté parce que tu m'as dit de le faire. Tu penses qu'il faut l'enlever?

2021-03-25 07:29 UTC, oliviermeslin commented on R/build_website.R
> +  }
C'est réglé

2021-03-25 07:53 UTC, RLesur commented on R/build_website.R
> +  }
Désolé, je n'ai pas été clair, je pensais à son utilisation pour le format basé sur `pagedown::html_paged()`.

2021-03-25 08:03 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
Ah oui... J'ai eu la flemme de trouver une autre solution...

2021-03-25 08:05 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      content: var(--date-fiche);
Résolu

2021-03-25 08:07 UTC, linogaliana commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +#  download: [["README.md", "PDF"]]
A rien, je vais enlever

2021-03-25 08:07 UTC, linogaliana commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +#  download: [["README.md", "PDF"]]
```suggestion
```

2021-03-25 08:08 UTC, linogaliana commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +  new_session: yes
Ah bon tu as essayé sans ? En effet, les fonctions de compilation forcent `new_session`

2021-03-25 08:11 UTC, oliviermeslin commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +  new_session: yes
Non, je fais tourner `test_template.R` systématiquement. Ca répond à ta question?

2021-03-25 08:11 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
@linogaliana : tu as une meilleure idée?

2021-03-25 08:12 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  footer[class="bg-primary text-light mt-5"] {
Si. C'est juste que je voulais être sûr de n'enlever que ce qui me dérange, vu qu'il y a un `display: none !important` juste après. Mais apparemment il n'y a qu'un seul `footer` par page.

2021-03-25 08:16 UTC, linogaliana commented on inst/templates/gitbook.html
> +
On ne devrait pas utiliser ce fichier. Je l'avais inclus au cas où de grosses modification de gitbook seraient nécessaires. Ce n'est plus le cas si on passe à bs4

2021-03-25 08:28 UTC, oliviermeslin commented on inst/templates/gitbook.html
> +
@linogaliana : donc ton idée c'est qu'on supprime `utilitr::html_document` à terme, pour ne garder que `utilitr::bs4_utilitr`? Moi ça me va

2021-03-25 08:35 UTC, linogaliana commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
Le modèle de site www.utilitr.org n'est pas géré dans le même dépôt ni de la même manière (hugo + blogdown).

Je me demande s'il ne serait pas mieux d'utiliser la valeur d'un paramètre de `render_book` ou du YAML de `_bookdown` passer ça au css (un truc du genre `url(monpetitlogo)`). C'est peut-être de l'overkill à court terme mais ça rendrait le modèle plus flexible

2021-03-25 08:37 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  div[class="chapter-nav"] {
Faut que je lise la doc sur les classes en CSS.

2021-03-25 08:40 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/default-page.css
> +*/
OK on peut les enlever. Je les ai commentées car j'aime pouvoir garder sous la main une option permettant de rajouter un cadre autour de la zone de texte.

2021-03-25 08:40 UTC, linogaliana commented on inst/rmarkdown/templates/utilitr/skeleton/_output.yml
> +  new_session: yes
Ok j'ai retiré, ça sert à rien

2021-03-25 08:42 UTC, linogaliana commented on inst/templates/gitbook.html
> +
On peut garder `utilitr::html_document` en backup pendant quelques temps. Mais il n'y a pas besoin d'utiliser notre modèle `gitbook` plutôt que celui de `bookdown`. Il s'agit juste de trouver où insérer ce code html ailleurs que dans `gitbook.html` (PS: c'est ignoré par `bs4` mais tu dois t'en douter)

2021-03-25 08:42 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/default.css
> + border-left: 2rem solid var(--background-color-chunk-output);
J'enlève

2021-03-25 08:42 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/default.css
> +*/
J'enlève

2021-03-25 08:43 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/default.css
> +*/
J'enlève

2021-03-25 08:45 UTC, oliviermeslin commented on inst/templates/gitbook.html
> +
> c'est ignoré par bs4 mais tu dois t'en douter

Oui, bs4 utilise `header_polyfill.html` et `print_button.html`.

2021-03-25 08:53 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
Je suis d'accord. En fait, je me demandais si on voulait que le logo `utilitR` soit dans le _package_ ou pas. Je pense qu'il est préférable qu'il n'y figure pas, justement pour permettre la réutilisation du modèle. Mais ça implique qu'on puisse définir le logo à un endroit, et je ne sais pas comment faire.

2021-03-25 08:59 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  .col-xl, .col-xl-auto, .col-xl-12, .col-xl-11, .col-xl-10, .col-xl-9, .col-xl-8, .col-xl-7, .col-xl-6, .col-xl-5, .col-xl-4, .col-xl-3, .col-xl-2, .col-xl-1, .col-lg, .col-lg-auto, .col-lg-12, .col
Ben je veux enlever le `padding` de plein de classes créées par `bootstrap`, sans modifier quoi que ce soit d'autre. Ces classes sont utilisées dans des éléments `div`, `header` et `main`, donc je préfère travailler sur les classes que sur les éléments car je risquerais d'avoir des effets de bord indésirables. Mais c'est pas très propre, je reconnais. 

Comment penses-tu qu'il faille faire?

2021-03-25 09:00 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +.col-md-9 {
De mémoire, c'est la solution au problème de largeur de la zone de texte en `print`. Si tu penses que `main` ça va marcher sans effets de bord, on peut le faire.

2021-03-25 10:13 UTC, linogaliana commented on R/build_website.R
> +#' @param extra_dependencies Additional HTML dependencies
@RLesur C'était ce que j'ai fait dans d68bf400cb0db6b13af6916ce9900d6b89417216  que tu avais à l'esprit ?

2021-03-25 16:50 UTC, linogaliana commented on R/build_website.R
> +  print(paste0("default_dep: ", default_dep))
```suggestion
```

pas besoin de ça

2021-03-26 06:32 UTC, RLesur commented on R/build_website.R
> +#' @param extra_dependencies Additional HTML dependencies
@linogaliana Exactement !

2021-03-26 06:37 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
@oliviermeslin lorsque tu veux faire ça, la bonne pratique est de stocker l'image avec les autres assets CSS et JS et ensuite d'y faire référence grâce à un chemin relatif. Tu te retrouves donc avec une librairie CSS + des images.

2021-03-26 06:38 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  footer[class="bg-primary text-light mt-5"] {
Sémantiquement, si les éléments `footer` sont bien utilisés, c'est-à-dire pour du contenu accessoire, c'est normalement safe.

2021-03-26 06:40 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +.col-md-9 {
Je n'en sais rien, je n'ai pas testé. Il faudrait peut-être simplement documenter l'élément que tu vises car cette classe est une classe bootstrap qui dit simplement "ce contenu occupe 9/12 de la largeur".

2021-03-26 06:41 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  .col-xl, .col-xl-auto, .col-xl-12, .col-xl-11, .col-xl-10, .col-xl-9, .col-xl-8, .col-xl-7, .col-xl-6, .col-xl-5, .col-xl-4, .col-xl-3, .col-xl-2, .col-xl-1, .col-lg, .col-lg-auto, .col-lg-12, .col
Eh bien je dirais qu'il faut simplement que tu rajoutes en commentaires dans le CSS ce que tu expliques ici.

2021-03-26 06:44 UTC, RLesur commented on inst/rmarkdown/resources/css/default-page.css
> +*/
Si c'est ton objectif, il faut que tu utilises [outline](https://developer.mozilla.org/fr/docs/Web/CSS/outline), c'est simplement une ligne et ça a pour bonne vertu de ne pas modifier la taille de tes boîtes :wink:

2021-03-26 06:59 UTC, RLesur approved these changes

2021-03-26 08:03 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
@RLesur: Merci pour l'explication, c'est exactement ce que j'avais en tête. Ce qui me fait hésiter, ce n'est pas tant le chemin relatif (je sais qu'en tâtonnant je vais y arriver) que le fait de mettre le logo `utilitR` dans un _package_ qui pourrait avoir un usage plus large que notre seule documentation.

2021-03-26 08:21 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/customize-bs4.css
> +  .col-xl, .col-xl-auto, .col-xl-12, .col-xl-11, .col-xl-10, .col-xl-9, .col-xl-8, .col-xl-7, .col-xl-6, .col-xl-5, .col-xl-4, .col-xl-3, .col-xl-2, .col-xl-1, .col-lg, .col-lg-auto, .col-lg-12, .col
C'est fait

2021-03-26 08:22 UTC, oliviermeslin commented on inst/rmarkdown/resources/css/default-page.css
> +*/
Entendu 📢

2021-03-26 09:07 UTC, linogaliana commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
Je pense qu'il ne faut pas mettre le logo utilitR dans un package dont on peut ne pas maîtriser l'usage. C'est pour ça que tous les exemples d'images (favicon, include_graphics...) utilisent un logo R.

On pourrait utiliser cette image à la place. Je me dis qu'on pourrait proposer une option `logo` de notre output format `utilitr_bs4` où `logo` pointe vers ce fichier. Mais, comment fait-on pour passer ce chemin au CSS ?

2021-03-27 09:08 UTC, RLesur commented on inst/rmarkdown/resources/css/customize-bs4.css
> +      background-image: url(https://www.utilitr.org/images/logo-utilitr.png);
@linogaliana je l'ai fait dans pagedown pour les covers : c'est une machinerie très lourde mais c'est techniquement faisable. Franchement, je pense qu'il est beaucoup plus facile de faire un petit CSS avec l'image dans le repo principal

2021-03-30 08:07 UTC, merged